### ISSUE TITLE
cisco.nxos.nxos_lag_interfaces module.

### ISSUE THREAD

**Issue by FDMGoMeZ** [NilashishC/cisco.nxos#11]
Hi NilashishC,

I am new to ansible so don't know if this a real issue but wanted to report it anyway.
I used the following test playbook.

---
- hosts: NXOSCLI
  gather_facts: no
  tasks:
    - name: Create LACP PORT-CHANNEL VPC PEER LINK
      cisco.nxos.nxos_lag_interfaces:
        config:
        - name: 10
          members:
            - member: Eth1/2
              mode: active

In the name field i needed to specify only the number and not Port-channel10.  
Documentation examples say otherwise.

https://docs.ansible.com/ansible/latest/collections/cisco/nxos/nxos_lag_interfaces_module.html#ansible-collections-cisco-nxos-nxos-lag-interfaces-module

If is use the same syntax as in documentation I was getting errors.

sco.nxos.nxos_lag_interfaces_payload_09w732et/ansible_cisco.nxos.nxos_lag_interfaces_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/config/lag_interfaces/lag_interfaces.py\", line 82, in execute_module\n  File \"/tmp/ansible_cisco.nxos.nxos_lag_interfaces_payload_09w732et/ansible_cisco.nxos.nxos_lag_interfaces_payload.zip/ansible/module_utils/connection.py\", line 195, in __rpc__\nansible.module_utils.connection.ConnectionError: channel-group Port-channel 10 mode active\r\r\n                                 ^\r\n% Invalid number at '^' marker.\r\n\rswitch(config-if)# \n",

**Comment by NilashishC** [comment]
@FDMGoMeZ please open this issue in the main upstream repo (https://github.com/ansible-collections/cisco.nxos) and not my fork. Thanks!
