### ISSUE TITLE
docs issue

### ISSUE THREAD

**Issue by NilashishC** [NilashishC/cisco.nxos#7]
##### SUMMARY
nxos_ospfv2 docs incorrect

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
cisco.nxos.nxos_ospfv2_module.rst

##### ANSIBLE VERSION
```
ansible 2.10.2
  config file = /Users/nchakrab/.ansible.cfg
  configured module search path = ['/Users/nchakrab/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/nchakrab/venvs/dev/lib/python3.6/site-packages/ansible
  executable location = /Users/nchakrab/venvs/dev/bin/ansible
  python version = 3.6.10 (default, Mar 10 2020, 22:24:30) [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.20.17)]

```

##### CONFIGURATION
```
None
```

##### OS / ENVIRONMENT
NX-OS 9.3.3

**Comment by dwightschrute99** [comment]
Files identified in the description:
* [`docs/cisco.nxos.nxos_ospfv2_module.rst`](https://github.com/NilashishC/nxos/blob/main/docs/cisco.nxos.nxos_ospfv2_module.rst)
* [`plugins/modules/nxos_ospfv2.py`](https://github.com/NilashishC/nxos/blob/main/plugins/modules/nxos_ospfv2.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dwightschrute99** [comment]
cc @mikewiebe @praveenramoorthy @samccann
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)
